In [4]:
import pandas as pd
import numpy as np
import sklearn as sk

#ANSO
#df = pd.read_csv("/Users/annesophieriis/Downloads/fatal-police-shootings-data.csv", sep=',', header=0)
#LEA
#df = pd.read_csv("LEA PATH", sep=',', header=0)
#TOSTI
#df = pd.read_csv("TOSTI PATH", sep=',', header=0)

id                           int64
name                        object
date                        object
manner_of_death             object
armed                       object
age                        float64
gender                      object
race                        object
city                        object
state                       object
signs_of_mental_illness       bool
threat_level                object
flee                        object
body_camera                   bool
longitude                  float64
latitude                   float64
is_geocoding_exact            bool
dtype: object

In [5]:
df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,longitude,latitude,is_geocoding_exact
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,-123.122,47.247,True
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,-122.892,45.487,True
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,-97.281,37.695,True
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,-122.422,37.763,True
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,-104.692,40.384,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5619,6148,NaN,2020-09-05,shot and Tasered,knife,NaN,M,NaN,Chicago,IL,False,attack,Not fleeing,True,-87.747,41.803,True
5620,6142,NaN,2020-09-06,shot,knife,NaN,M,NaN,Summerlin,NV,False,attack,Not fleeing,False,NaN,NaN,True
5621,6144,Refugio Reynaldo Olivo,2020-09-06,shot,knife,49.0,M,NaN,Virginia Beach,VA,False,other,Not fleeing,False,-76.083,36.831,True
5622,6145,Verlon Billy Stiles,2020-09-06,shot,knife,54.0,M,NaN,Spruce Pine,NC,False,other,NaN,False,-82.065,35.918,True
5623,6140,Jeffrey Meyer,2020-09-07,shot,gun,51.0,M,W,Altoona,IA,False,other,NaN,False,-93.498,41.661,True

In [6]:
df.dtypes
#maybe split date so we can sort per year?
#handle missing data in most columns
#maybe drop ' is-geocoding-exact'
#is name relevant?
#consider 'threat_level' - what does this mean?
#maybe use the longitude and latitude to make a heat map? where most deaths happen

id                           int64
name                        object
date                        object
manner_of_death             object
armed                       object
age                        float64
gender                      object
race                        object
city                        object
state                       object
signs_of_mental_illness       bool
threat_level                object
flee                        object
body_camera                   bool
longitude                  float64
latitude                   float64
is_geocoding_exact            bool
dtype: object